// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_message.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	user_message.proto

It has these top-level messages:
	SqlRequest
	QueryResponse
	Row
	Column
	ExecResponse
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SqlRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Sql string `protobuf:"bytes,2,opt,name=sql" json:"sql,omitempty"`
}

func (m *SqlRequest) Reset()                    { *m = SqlRequest{} }
func (m *SqlRequest) String() string            { return proto.CompactTextString(m) }
func (*SqlRequest) ProtoMessage()               {}
func (*SqlRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SqlRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SqlRequest) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

type QueryResponse struct {
	Rows []*Row `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryResponse) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Row struct {
	Columns []*Column `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Row) GetColumns() []*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

type Column struct {
	Value *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *Column) Reset()                    { *m = Column{} }
func (m *Column) String() string            { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()               {}
func (*Column) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Column) GetValue() *google_protobuf.StringValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type ExecResponse struct {
	RowsAffected   int64 `protobuf:"varint,1,opt,name=rowsAffected" json:"rowsAffected,omitempty"`
	LastInsertedId int64 `protobuf:"varint,2,opt,name=lastInsertedId" json:"lastInsertedId,omitempty"`
}

func (m *ExecResponse) Reset()                    { *m = ExecResponse{} }
func (m *ExecResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()               {}
func (*ExecResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExecResponse) GetRowsAffected() int64 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

func (m *ExecResponse) GetLastInsertedId() int64 {
	if m != nil {
		return m.LastInsertedId
	}
	return 0
}

func init() {
	proto.RegisterType((*SqlRequest)(nil), "protos.SqlRequest")
	proto.RegisterType((*QueryResponse)(nil), "protos.QueryResponse")
	proto.RegisterType((*Row)(nil), "protos.Row")
	proto.RegisterType((*Column)(nil), "protos.Column")
	proto.RegisterType((*ExecResponse)(nil), "protos.ExecResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserMessage service

type UserMessageClient interface {
	Query(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Exec(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*ExecResponse, error)
}

type userMessageClient struct {
	cc *grpc.ClientConn
}

func NewUserMessageClient(cc *grpc.ClientConn) UserMessageClient {
	return &userMessageClient{cc}
}

func (c *userMessageClient) Query(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/protos.UserMessage/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMessageClient) Exec(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := grpc.Invoke(ctx, "/protos.UserMessage/Exec", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserMessage service

type UserMessageServer interface {
	Query(context.Context, *SqlRequest) (*QueryResponse, error)
	Exec(context.Context, *SqlRequest) (*ExecResponse, error)
}

func RegisterUserMessageServer(s *grpc.Server, srv UserMessageServer) {
	s.RegisterService(&_UserMessage_serviceDesc, srv)
}

func _UserMessage_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMessageServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserMessage/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMessageServer).Query(ctx, req.(*SqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMessage_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMessageServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserMessage/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMessageServer).Exec(ctx, req.(*SqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserMessage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.UserMessage",
	HandlerType: (*UserMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _UserMessage_Query_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _UserMessage_Exec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_message.proto",
}

func init() { proto.RegisterFile("user_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x37, 0xbb, 0x4d, 0x7c, 0x9d, 0x43, 0x82, 0xc2, 0x18, 0x82, 0x23, 0x07, 0xd9, 0xa9,
	0x8e, 0xea, 0xd1, 0x8b, 0x88, 0x87, 0x1d, 0x3c, 0x98, 0xa1, 0x07, 0x2f, 0xd2, 0x6d, 0x6f, 0x45,
	0xcc, 0x9a, 0x36, 0x2f, 0xb1, 0xee, 0xbf, 0x97, 0x26, 0x46, 0x9d, 0x78, 0x4a, 0xf8, 0xbd, 0x2f,
	0x8f, 0xef, 0xfb, 0x02, 0xcc, 0x12, 0xea, 0x97, 0x0d, 0x12, 0x65, 0x39, 0x26, 0xa5, 0x56, 0x46,
	0xb1, 0x9e, 0x3b, 0x68, 0x34, 0xa8, 0x75, 0x56, 0x96, 0xa8, 0xc9, 0x73, 0x3e, 0x05, 0x98, 0x57,
	0x52, 0x60, 0x65, 0x91, 0x0c, 0x3b, 0x82, 0xe8, 0x0d, 0xb7, 0xc3, 0xf6, 0xb8, 0x3d, 0x39, 0x10,
	0xcd, 0xb5, 0x21, 0x54, 0xc9, 0xe1, 0x9e, 0x27, 0x54, 0x49, 0x3e, 0x85, 0xc3, 0x07, 0x8b, 0x7a,
	0x2b, 0x90, 0x4a, 0x55, 0x10, 0xb2, 0x33, 0xe8, 0x68, 0x55, 0xd3, 0xb0, 0x3d, 0x8e, 0x26, 0x71,
	0x1a, 0xfb, 0xc5, 0x94, 0x08, 0x55, 0x0b, 0x37, 0xe0, 0x17, 0x10, 0x09, 0x55, 0xb3, 0x09, 0xec,
	0x2f, 0x95, 0xb4, 0x9b, 0x22, 0x48, 0x07, 0x41, 0x7a, 0xeb, 0xb0, 0x08, 0x63, 0x7e, 0x0d, 0x3d,
	0x8f, 0x58, 0x0a, 0xdd, 0xf7, 0x4c, 0x5a, 0x74, 0x96, 0xe2, 0xf4, 0x34, 0xc9, 0x95, 0xca, 0xe5,
	0x57, 0xa8, 0x85, 0x5d, 0x27, 0x73, 0xa3, 0x5f, 0x8b, 0xfc, 0xa9, 0xd1, 0x08, 0x2f, 0xe5, 0xcf,
	0xd0, 0xbf, 0xfb, 0xc0, 0xe5, 0xb7, 0x3f, 0x0e, 0xfd, 0xc6, 0xc6, 0xcd, 0x7a, 0x8d, 0x4b, 0x83,
	0x2b, 0xb7, 0x2a, 0x12, 0x3b, 0x8c, 0x9d, 0xc3, 0x40, 0x66, 0x64, 0x66, 0x05, 0xa1, 0x36, 0xb8,
	0x9a, 0xad, 0x5c, 0xe2, 0x48, 0xfc, 0xa1, 0x69, 0x0d, 0xf1, 0x23, 0xa1, 0xbe, 0xf7, 0xdd, 0xb2,
	0x2b, 0xe8, 0xba, 0x2e, 0x18, 0x0b, 0x51, 0x7e, 0xca, 0x1c, 0x9d, 0x04, 0xb6, 0x53, 0x17, 0x6f,
	0xb1, 0x14, 0x3a, 0x8d, 0xc1, 0x7f, 0x1f, 0x1d, 0x07, 0xf6, 0x3b, 0x02, 0x6f, 0x2d, 0xfc, 0xff,
	0x5d, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xa2, 0x3a, 0xde, 0xdc, 0x01, 0x00, 0x00,
}
