// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_message.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	user_message.proto

It has these top-level messages:
	SqlRequest
	QueryResponse
	Row
	Column
	ExecResponse
	KeyData
	SimpleResult
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SqlRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Sql string `protobuf:"bytes,2,opt,name=sql" json:"sql,omitempty"`
}

func (m *SqlRequest) Reset()                    { *m = SqlRequest{} }
func (m *SqlRequest) String() string            { return proto.CompactTextString(m) }
func (*SqlRequest) ProtoMessage()               {}
func (*SqlRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SqlRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SqlRequest) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

type QueryResponse struct {
	Rows []*Row `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryResponse) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Row struct {
	Columns []*Column `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Row) GetColumns() []*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

type Column struct {
	Value *google_protobuf.StringValue `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *Column) Reset()                    { *m = Column{} }
func (m *Column) String() string            { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()               {}
func (*Column) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Column) GetValue() *google_protobuf.StringValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type ExecResponse struct {
	RowsAffected   int64 `protobuf:"varint,1,opt,name=rowsAffected" json:"rowsAffected,omitempty"`
	LastInsertedId int64 `protobuf:"varint,2,opt,name=lastInsertedId" json:"lastInsertedId,omitempty"`
}

func (m *ExecResponse) Reset()                    { *m = ExecResponse{} }
func (m *ExecResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecResponse) ProtoMessage()               {}
func (*ExecResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExecResponse) GetRowsAffected() int64 {
	if m != nil {
		return m.RowsAffected
	}
	return 0
}

func (m *ExecResponse) GetLastInsertedId() int64 {
	if m != nil {
		return m.LastInsertedId
	}
	return 0
}

type KeyData struct {
	Key       string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	ShardName string `protobuf:"bytes,2,opt,name=shardName" json:"shardName,omitempty"`
}

func (m *KeyData) Reset()                    { *m = KeyData{} }
func (m *KeyData) String() string            { return proto.CompactTextString(m) }
func (*KeyData) ProtoMessage()               {}
func (*KeyData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *KeyData) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyData) GetShardName() string {
	if m != nil {
		return m.ShardName
	}
	return ""
}

type SimpleResult struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *SimpleResult) Reset()                    { *m = SimpleResult{} }
func (m *SimpleResult) String() string            { return proto.CompactTextString(m) }
func (*SimpleResult) ProtoMessage()               {}
func (*SimpleResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SimpleResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SimpleResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SqlRequest)(nil), "protos.SqlRequest")
	proto.RegisterType((*QueryResponse)(nil), "protos.QueryResponse")
	proto.RegisterType((*Row)(nil), "protos.Row")
	proto.RegisterType((*Column)(nil), "protos.Column")
	proto.RegisterType((*ExecResponse)(nil), "protos.ExecResponse")
	proto.RegisterType((*KeyData)(nil), "protos.KeyData")
	proto.RegisterType((*SimpleResult)(nil), "protos.SimpleResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserMessage service

type UserMessageClient interface {
	Query(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Exec(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	RegisterKey(ctx context.Context, in *KeyData, opts ...grpc.CallOption) (*SimpleResult, error)
	RemoveKey(ctx context.Context, in *KeyData, opts ...grpc.CallOption) (*SimpleResult, error)
}

type userMessageClient struct {
	cc *grpc.ClientConn
}

func NewUserMessageClient(cc *grpc.ClientConn) UserMessageClient {
	return &userMessageClient{cc}
}

func (c *userMessageClient) Query(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/protos.UserMessage/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMessageClient) Exec(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	out := new(ExecResponse)
	err := grpc.Invoke(ctx, "/protos.UserMessage/Exec", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMessageClient) RegisterKey(ctx context.Context, in *KeyData, opts ...grpc.CallOption) (*SimpleResult, error) {
	out := new(SimpleResult)
	err := grpc.Invoke(ctx, "/protos.UserMessage/RegisterKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userMessageClient) RemoveKey(ctx context.Context, in *KeyData, opts ...grpc.CallOption) (*SimpleResult, error) {
	out := new(SimpleResult)
	err := grpc.Invoke(ctx, "/protos.UserMessage/RemoveKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserMessage service

type UserMessageServer interface {
	Query(context.Context, *SqlRequest) (*QueryResponse, error)
	Exec(context.Context, *SqlRequest) (*ExecResponse, error)
	RegisterKey(context.Context, *KeyData) (*SimpleResult, error)
	RemoveKey(context.Context, *KeyData) (*SimpleResult, error)
}

func RegisterUserMessageServer(s *grpc.Server, srv UserMessageServer) {
	s.RegisterService(&_UserMessage_serviceDesc, srv)
}

func _UserMessage_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMessageServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserMessage/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMessageServer).Query(ctx, req.(*SqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMessage_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMessageServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserMessage/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMessageServer).Exec(ctx, req.(*SqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMessage_RegisterKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMessageServer).RegisterKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserMessage/RegisterKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMessageServer).RegisterKey(ctx, req.(*KeyData))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserMessage_RemoveKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMessageServer).RemoveKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserMessage/RemoveKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMessageServer).RemoveKey(ctx, req.(*KeyData))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserMessage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.UserMessage",
	HandlerType: (*UserMessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _UserMessage_Query_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _UserMessage_Exec_Handler,
		},
		{
			MethodName: "RegisterKey",
			Handler:    _UserMessage_RegisterKey_Handler,
		},
		{
			MethodName: "RemoveKey",
			Handler:    _UserMessage_RemoveKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_message.proto",
}

func init() { proto.RegisterFile("user_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0xef, 0x4c, 0xdb, 0xf3, 0x26, 0xe7, 0x29, 0x8b, 0xc2, 0x51, 0x0a, 0x96, 0x7d, 0x90,
	0x7b, 0x8a, 0x25, 0x16, 0x41, 0xf0, 0xc5, 0x5f, 0x0f, 0xa5, 0x28, 0xb8, 0x87, 0x3e, 0xf8, 0x22,
	0xdb, 0x64, 0x2e, 0x1e, 0x6e, 0xb2, 0xc9, 0xce, 0x6e, 0x63, 0xfe, 0x60, 0xff, 0x0f, 0xc9, 0x26,
	0xeb, 0xb5, 0xd2, 0x17, 0x9f, 0x92, 0xf9, 0xcc, 0x77, 0x86, 0x99, 0xef, 0x2c, 0x30, 0x47, 0x68,
	0xbe, 0x97, 0x48, 0x24, 0x0b, 0x4c, 0x6a, 0xa3, 0xad, 0x66, 0x47, 0xfe, 0x43, 0xc7, 0xcb, 0xd6,
	0xc8, 0xba, 0x46, 0x43, 0x03, 0xe7, 0x67, 0x00, 0x9b, 0x46, 0x09, 0x6c, 0x1c, 0x92, 0x65, 0x8f,
	0x20, 0xfa, 0x89, 0xdd, 0x6a, 0x7a, 0x3a, 0x5d, 0xcf, 0x45, 0xff, 0xdb, 0x13, 0x6a, 0xd4, 0xea,
	0xde, 0x40, 0xa8, 0x51, 0xfc, 0x0c, 0x1e, 0x7c, 0x76, 0x68, 0x3a, 0x81, 0x54, 0xeb, 0x8a, 0x90,
	0x3d, 0x85, 0x03, 0xa3, 0x5b, 0x5a, 0x4d, 0x4f, 0xa3, 0x75, 0x9c, 0xc6, 0x43, 0x63, 0x4a, 0x84,
	0x6e, 0x85, 0x4f, 0xf0, 0xe7, 0x10, 0x09, 0xdd, 0xb2, 0x35, 0xcc, 0x32, 0xad, 0x5c, 0x59, 0x05,
	0xe9, 0x32, 0x48, 0xdf, 0x79, 0x2c, 0x42, 0x9a, 0xbf, 0x86, 0xa3, 0x01, 0xb1, 0x14, 0x0e, 0xaf,
	0xa5, 0x72, 0xe8, 0x47, 0x8a, 0xd3, 0x93, 0xa4, 0xd0, 0xba, 0x50, 0xe3, 0x52, 0x57, 0x6e, 0x9b,
	0x6c, 0xac, 0xd9, 0x55, 0xc5, 0xd7, 0x5e, 0x23, 0x06, 0x29, 0xff, 0x06, 0x8b, 0x0f, 0xbf, 0x30,
	0xfb, 0x3b, 0x1f, 0x87, 0x45, 0x3f, 0xc6, 0x9b, 0xed, 0x16, 0x33, 0x8b, 0xb9, 0x6f, 0x15, 0x89,
	0x5b, 0x8c, 0x3d, 0x83, 0xa5, 0x92, 0x64, 0x2f, 0x2a, 0x42, 0x63, 0x31, 0xbf, 0xc8, 0xfd, 0xc6,
	0x91, 0xf8, 0x87, 0xf2, 0x57, 0x30, 0xbb, 0xc4, 0xee, 0xbd, 0xb4, 0xf2, 0x0e, 0xaf, 0x4e, 0x60,
	0x4e, 0x3f, 0xa4, 0xc9, 0x3f, 0xc9, 0x12, 0x47, 0xc7, 0xf6, 0x80, 0xbf, 0x85, 0xc5, 0x66, 0x57,
	0xd6, 0x0a, 0x05, 0x92, 0x53, 0x96, 0xad, 0x60, 0x46, 0x2e, 0xcb, 0x90, 0xc8, 0xf7, 0xb8, 0x2f,
	0x42, 0xd8, 0x67, 0xc6, 0xe3, 0x8d, 0x5d, 0x42, 0x98, 0xfe, 0x9e, 0x42, 0xfc, 0x85, 0xd0, 0x7c,
	0x1c, 0x62, 0x76, 0x0e, 0x87, 0xfe, 0x16, 0x8c, 0x05, 0x2b, 0xf7, 0xc7, 0x3c, 0x7e, 0x12, 0xd8,
	0xad, 0x73, 0xf1, 0x09, 0x4b, 0xe1, 0xa0, 0x37, 0xe8, 0xce, 0xa2, 0xc7, 0x81, 0xdd, 0xb4, 0x90,
	0x4f, 0xd8, 0x4b, 0x88, 0x05, 0x16, 0x3b, 0xb2, 0x68, 0x2e, 0xb1, 0x63, 0x0f, 0x83, 0x6c, 0x74,
	0x63, 0x5f, 0x77, 0x73, 0x47, 0x3e, 0x61, 0xe7, 0x30, 0x17, 0x58, 0xea, 0x6b, 0xfc, 0x9f, 0xaa,
	0xab, 0xe1, 0xb5, 0xbe, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x21, 0x26, 0xbf, 0xca, 0x02,
	0x00, 0x00,
}
